// @ts-nocheck
import { describe, it } from "node:test";
import assert from "node:assert";

function isRetryable(err){if(!err||typeof err!=="object")return false;const msg=err?.message??"";if(/^HTTP (429|500|502|503|504):/.test(msg))return true;return err?.code==="ECONNRESET"||err?.code==="ECONNREFUSED"||err?.code==="ETIMEDOUT"||msg.includes("socket hang up")||msg.includes("ECONNRESET")||msg.includes("ETIMEDOUT")||msg.includes("ECONNREFUSED")||msg.includes("request timeout")||msg.includes("stream idle timeout");}

describe("B1 HTTP 429/5xx retryable",()=>{["429","500","502","503","504"].forEach(c=>{it("HTTP "+c+" retryable",()=>assert.ok(isRetryable(new Error("HTTP "+c+": x"))));});});
describe("B2 HTTP 4xx non-retryable",()=>{["400","401","403","404"].forEach(c=>{it("HTTP "+c+" NOT retryable",()=>assert.strictEqual(isRetryable(new Error("HTTP "+c+": x")),false));});});
describe("B3 Network errors retryable",()=>{it("ECONNREFUSED",()=>{const e=new Error("connect ECONNREFUSED");e.code="ECONNREFUSED";assert.ok(isRetryable(e));});it("ECONNRESET",()=>{const e=new Error("ECONNRESET");e.code="ECONNRESET";assert.ok(isRetryable(e));});it("ETIMEDOUT",()=>{const e=new Error("ETIMEDOUT");e.code="ETIMEDOUT";assert.ok(isRetryable(e));});it("socket hang up",()=>assert.ok(isRetryable(new Error("socket hang up"))));it("request timeout",()=>assert.ok(isRetryable(new Error("request timeout"))));it("stream idle timeout",()=>assert.ok(isRetryable(new Error("stream idle timeout"))));});
describe("B4 AbortError NOT retryable",()=>{it("AbortError",()=>{const e=new Error("aborted");e.name="AbortError";assert.strictEqual(isRetryable(e),false);});});
describe("B5 DNS errors NOT retryable",()=>{it("ENOTFOUND",()=>{const e=new Error("");e.code="ENOTFOUND";assert.strictEqual(isRetryable(e),false);});it("EAI_AGAIN",()=>{const e=new Error("");e.code="EAI_AGAIN";assert.strictEqual(isRetryable(e),false);});});
describe("B6 Empty/invalid response",()=>{it("empty choices",()=>assert.strictEqual(JSON.parse("{\"choices\":[]}").choices.length,0));it("invalid JSON throws SyntaxError",()=>assert.throws(()=>JSON.parse("not json"),SyntaxError));it("missing choices undefined",()=>assert.strictEqual(JSON.parse("{\"id\":\"x\"}").choices,undefined));});
describe("B7 Retry exhaustion",()=>{it("attempt 2 still retries",()=>{assert.strictEqual(2<3,true);assert.ok(isRetryable(new Error("HTTP 503: x")));});it("attempt 3 stops retry",()=>assert.strictEqual(3>=3,true));});
describe("B8 Multi-match code+msg",()=>{it("ECONNRESET+socket hang up",()=>{const e=new Error("socket hang up");e.code="ECONNRESET";assert.ok(isRetryable(e));});it("ETIMEDOUT+ECONNREFUSED",()=>{const e=new Error("ECONNREFUSED");e.code="ETIMEDOUT";assert.ok(isRetryable(e));});});
describe("B9 Only code matches",()=>{it("ECONNRESET empty msg",()=>{const e=new Error("");e.code="ECONNRESET";assert.ok(isRetryable(e));});it("ECONNREFUSED empty msg",()=>{const e=new Error("");e.code="ECONNREFUSED";assert.ok(isRetryable(e));});it("ETIMEDOUT empty msg",()=>{const e=new Error("");e.code="ETIMEDOUT";assert.ok(isRetryable(e));});});
describe("B10 Only message matches",()=>{it("socket hang up",()=>assert.ok(isRetryable(new Error("socket hang up"))));it("ECONNRESET",()=>assert.ok(isRetryable(new Error("ECONNRESET"))));it("request timeout",()=>assert.ok(isRetryable(new Error("request timeout"))));it("stream idle timeout",()=>assert.ok(isRetryable(new Error("stream idle timeout"))));});
describe("Edge null/undefined/malformed",()=>{it("null",()=>assert.strictEqual(isRetryable(null),false));it("undefined",()=>assert.strictEqual(isRetryable(undefined),false));it("empty object",()=>assert.strictEqual(isRetryable({}),false));it("string",()=>assert.strictEqual(isRetryable("err"),false));it("number",()=>assert.strictEqual(isRetryable(42),false));it("object with code only",()=>assert.ok(isRetryable({code:"ECONNRESET"})));it("object with msg only",()=>assert.ok(isRetryable({message:"request timeout"})));});
