import { Keybinding } from '../engine/types.js';

export const defaultKeybindings: Keybinding[] = [
  { key: 's',       action: 'spawn',       description: 'Spawn a new agent' },
  { key: 'f',       action: 'fork',        description: 'Fork from selected spawn' },
  { key: 'p',       action: 'pause',       description: 'Pause selected agent' },
  { key: 'r',       action: 'resume',      description: 'Resume selected agent' },
  { key: 't',       action: 'terminate',   description: 'Terminate selected agent' },
  { key: 'm',       action: 'memory:set',  description: 'Set memory key' },
  { key: 'd',       action: 'memory:del',  description: 'Delete memory key' },
  { key: 'c',       action: 'memory:clear',description: 'Clear all memory' },
  { key: 'v',       action: 'view:toggle', description: 'Toggle cards/tree/swarm view' },
  { key: 't',       action: 'theme:cycle', description: 'Cycle theme' },
  { key: 'escape',  action: 'cancel',      description: 'Cancel / dismiss' },
  { key: 'enter',   action: 'confirm',     description: 'Confirm selection' },
  { key: 'q',       action: 'quit',        description: 'Quit' },
  { key: 'up',      action: 'move:up',     description: 'Move selection up' },
  { key: 'down',    action: 'move:down',   description: 'Move selection down' },
  { key: 'home',    action: 'move:top',    description: 'Move to first item' },
  { key: 'end',     action: 'move:bottom', description: 'Move to last item' },
  { key: 'pageup',  action: 'move:pageup', description: 'Scroll page up' },
  { key: 'pagedown',action: 'move:pagedown',description: 'Scroll page down' },
  { key: 'tab',     action: 'panel:next',  description: 'Switch to next panel' },
  { key: '/',       action: 'command',     description: 'Open command palette' },
  { key: '?',       action: 'help',        description: 'Show help' },
];

export const keybindDescriptions: Record<string, string> = {
  'spawn':          'Spawn a new SpawnAgent',
  'fork':           'Fork a ForkAgent from selected spawn',
  'pause':          'Pause the selected agent',
  'resume':         'Resume the selected agent',
  'terminate':      'Terminate the selected agent',
  'memory:set':     'Set a memory key-value pair',
  'memory:del':     'Delete a memory key',
  'memory:clear':   'Clear all memory in selected spawn',
  'view:toggle':    'Toggle between tree and swarm view',
  'cancel':         'Cancel current operation',
  'confirm':        'Confirm / execute',
  'quit':           'Quit SpawnTUI',
  'move:up':        'Move selection up',
  'move:down':      'Move selection down',
  'move:top':       'Jump to first item',
  'move:bottom':    'Jump to last item',
  'move:pageup':    'Scroll up one page',
  'move:pagedown':  'Scroll down one page',
  'panel:next':     'Switch focus to next panel',
  'command':        'Open the command palette',
  'help':           'Show keybinding help',
};
